# Generated by Django 3.2.25 on 2025-06-30 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="format",
            field=models.ForeignKey(
                help_text="Format of the audio file.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="files",
                to="data.fileformat",
            ),
        ),
    ]
