# Generated by Django 3.2.25 on 2025-07-23 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_alter_file_format"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"ordering": ("filename",)},
        ),
        migrations.AlterModelOptions(
            name="fileformat",
            options={"ordering": ("name",)},
        ),
        migrations.AlterField(
            model_name="file",
            name="audio_properties",
            field=models.OneToOneField(
                blank=True,
                help_text="Each property is dedicated to one file.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file",
                to="data.audioproperties",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="detection_properties",
            field=models.OneToOneField(
                blank=True,
                help_text="Each property is dedicated to one file.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file",
                to="data.detectionproperties",
            ),
        ),
    ]
