# Generated by Django 3.2.25 on 2025-08-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_clean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioproperties',
            options={'verbose_name_plural': 'Audio Properties'},
        ),
        migrations.AlterModelOptions(
            name='detectionproperties',
            options={'verbose_name_plural': 'DetectionProperties'},
        ),
    ]
