# Generated by Django 3.2.25 on 2025-12-10 10:25
from django.db import migrations, models
import django.db.models.deletion


def migrate(apps, _):
    File = apps.get_model("data", "File")
    ContentType = apps.get_model("contenttypes", "ContentType")

    for f in File.objects.all():
        if f.audio_properties is not None:
            f.property_type = ContentType.objects.get_for_model(f.audio_properties)
            f.property_id = f.audio_properties.id
        elif f.detection_properties is not None:
            f.property_type = ContentType.objects.get_for_model(f.detection_properties)
            f.property_id = f.detection_properties.id
        f.save()


def reverse_migrate(apps, _):
    File = apps.get_model("data", "File")

    for f in File.objects.all():
        if f.property_type.name == "audioproperties":
            f.audio_properties = f.property
        elif f.property_type.name == 'detectionproperties':
            f.detection_properties = f.property
        f.save()


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data', '0004_alter_verbose_name_plural_for_properties'),
    ]

    operations = [
        # Add content type
        migrations.AddField(
            model_name='file',
            name='property_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AddField(
            model_name='file',
            name='property_type',
            field=models.ForeignKey(limit_choices_to={
                'model__in': ['data.AudioProperties', 'data.DetectionProperties']},
                on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        # Migrate
        migrations.RunPython(migrate, reverse_migrate),
        # Remove old fields
        migrations.RemoveField(
            model_name='file',
            name='audio_properties',
        ),
        migrations.RemoveField(
            model_name='file',
            name='detection_properties',
        ),
        # Rename tables
        migrations.AlterModelTable(
            name='audioproperties',
            table='mx_data_audioproperties',
        ),
        migrations.AlterModelTable(
            name='detectionproperties',
            table='mx_data_detectionproperties',
        ),
        migrations.AlterModelTable(
            name='file',
            table='mx_data_file',
        ),
        migrations.AlterModelTable(
            name='fileformat',
            table='mx_data_fileformat',
        ),
    ]
