# Generated by Django 3.2.25 on 2025-12-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_refacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('data.file',),
        ),
        migrations.CreateModel(
            name='DetectionFile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('data.file',),
        ),
    ]
