# Generated by Django 4.2.29 on 2026-07-28 12:10

from django.db import migrations, models
import django.db.models.deletion
import metadatax.utils.custom_fields.datetime


class Migration(migrations.Migration):

    dependencies = [
        ("acquisition", "0015_channelconfiguration_status_to_islost_clean"),
        ("ontology", "0006_behavior"),
        ("data", "0006_audiofile_detectionfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_datetime",
                    metadatax.utils.custom_fields.datetime.DateTimeField(
                        help_text="Start datetime for the observation."
                    ),
                ),
                (
                    "end_datetime",
                    metadatax.utils.custom_fields.datetime.DateTimeField(
                        help_text="End datetime for the observation."
                    ),
                ),
                (
                    "count_min",
                    models.IntegerField(
                        blank=True,
                        help_text="Minimal number of source observed.",
                        null=True,
                    ),
                ),
                (
                    "count_max",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximal number of source observed.",
                        null=True,
                    ),
                ),
                (
                    "start_distance_min",
                    models.IntegerField(
                        blank=True,
                        help_text="Minimal distance at the start of the observation.",
                        null=True,
                    ),
                ),
                (
                    "start_distance_max",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximal distance at the start of the observation.",
                        null=True,
                    ),
                ),
                (
                    "end_distance_min",
                    models.IntegerField(
                        blank=True,
                        help_text="Minimal distance at the end of the observation.",
                        null=True,
                    ),
                ),
                (
                    "end_distance_max",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximal distance at the end of the observation.",
                        null=True,
                    ),
                ),
                (
                    "young_presence",
                    models.BooleanField(
                        blank=True,
                        help_text="Young animals presence during the observation.",
                        null=True,
                    ),
                ),
                (
                    "other_human_activity_presence",
                    models.BooleanField(
                        blank=True,
                        help_text="Human activity presence during the observation (excluding the observation process).",
                        null=True,
                    ),
                ),
                (
                    "additional_information",
                    models.TextField(
                        blank=True,
                        help_text="Optional information over the observation.",
                        null=True,
                    ),
                ),
                (
                    "behaviors",
                    models.ManyToManyField(
                        related_name="visual_observations", to="ontology.behavior"
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visual_observations",
                        to="acquisition.deployment",
                    ),
                ),
                (
                    "reactions_to_boat",
                    models.ManyToManyField(
                        related_name="visual_observation_reactions",
                        to="ontology.behavior",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visual_observations",
                        to="ontology.source",
                    ),
                ),
            ],
            options={
                "db_table": "mx_data_visualobservation",
            },
        ),
    ]
