# Generated by Django 4.2.29 on 2026-08-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0006_behavior"),
        ("data", "0007_visualobservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visualobservation",
            name="behaviors",
            field=models.ManyToManyField(
                blank=True, related_name="visual_observations", to="ontology.behavior"
            ),
        ),
        migrations.AlterField(
            model_name="visualobservation",
            name="reactions_to_boat",
            field=models.ManyToManyField(
                blank=True,
                related_name="visual_observation_reactions",
                to="ontology.behavior",
            ),
        ),
    ]
