# Generated by Django 3.2.25 on 2025-06-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('mail', models.EmailField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MC', 'Main Contact'), ('F', 'Funder'), ('PO', 'Project Owner'), ('PM', 'Project Manager'), ('DS', 'Dataset Supplier'), ('DP', 'Dataset Producer'), ('PD', 'Production Database'), ('CP', 'Contact Point')], max_length=2)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadatax_common.contact')),
            ],
            options={
                'unique_together': {('contact', 'role')},
            },
        ),
    ]
