# Generated by Django 3.2.25 on 2025-07-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibliography", "0001_initial"),
        ("ontology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="related_bibliography",
            field=models.ManyToManyField(
                related_name="related_labels", to="bibliography.Bibliography"
            ),
        ),
        migrations.AddField(
            model_name="physicaldescriptor",
            name="related_bibliography",
            field=models.ManyToManyField(
                related_name="related_physical_descriptors",
                to="bibliography.Bibliography",
            ),
        ),
        migrations.AddField(
            model_name="sound",
            name="related_bibliography",
            field=models.ManyToManyField(
                related_name="related_sounds", to="bibliography.Bibliography"
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="related_bibliography",
            field=models.ManyToManyField(
                related_name="related_sources", to="bibliography.Bibliography"
            ),
        ),
    ]
