# Generated by Django 3.2.25 on 2025-07-23 15:38

import django.core.validators
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0003_related_bibliography_is_optional"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="label",
            options={"ordering": ("nickname", "source", "sound")},
        ),
        migrations.AlterModelOptions(
            name="physicaldescriptor",
            options={"ordering": ("label",)},
        ),
        migrations.AlterModelOptions(
            name="sound",
            options={"ordering": ["english_name"]},
        ),
        migrations.AlterModelOptions(
            name="source",
            options={"ordering": ["english_name"]},
        ),
        migrations.RemoveField(
            model_name="sound",
            name="associated_names",
        ),
        migrations.AddField(
            model_name="label",
            name="associated_names",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255, null=True),
                blank=True,
                help_text="Other name found in the bibliography for this label",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterModelOptions(
            name="label",
            options={"ordering": ("source", "sound", "nickname")},
        ),
        migrations.AddField(
            model_name="label",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="label",
            name="max_frequency",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="label",
            name="mean_duration",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="min_frequency",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="label",
            name="plurality",
            field=models.TextField(
                blank=True,
                choices=[("O", "One"), ("S", "Set"), ("RS", "Repetitive Set")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="shape",
            field=models.TextField(
                blank=True,
                choices=[
                    ("S", "Stationary"),
                    ("P", "Pulse"),
                    ("FM", "Frequency modulation"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.RunSQL(
            sql="\n            UPDATE metadatax_ontology_label l\n            SET\n                description=d.description,\n                max_frequency=d.max_frequency,\n                mean_duration=d.mean_duration,\n                min_frequency=d.min_frequency,\n                plurality=d.plurality,\n                shape=d.shape\n            FROM metadatax_ontology_physicaldescriptor d\n            WHERE l.id=d.label_id\n        ",
        ),
        migrations.DeleteModel(
            name="PhysicalDescriptor",
        ),
        migrations.AlterUniqueTogether(
            name="label",
            unique_together={("source", "sound", "nickname")},
        ),
        migrations.AddField(
            model_name="label",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="ontology.label",
            ),
        ),
    ]
