# Generated by Django 3.2.25 on 2025-12-11 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ontology', '0004_clean'),
        ('metadatax', '0027_reset_indexes')
    ]

    operations = [
        migrations.AlterModelTable(
            name='label',
            table='mx_ontology_label',
        ),
        migrations.AlterModelTable(
            name='sound',
            table='mx_ontology_sound',
        ),
        migrations.AlterModelTable(
            name='source',
            table='mx_ontology_source',
        ),
    ]
