# Generated by Django 4.2.29 on 2026-07-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0005_table_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="Behavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "mx_ontology_behavior",
                "ordering": ["name"],
            },
        ),
    ]
