# Generated by Django 3.2.25 on 2024-05-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accept_mailing",
            field=models.BooleanField(default=False),
        ),
    ]
