# Generated by Django 3.2.25 on 2024-05-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_auth", "0002_user_accept_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
