# Generated by Django 3.2.25 on 2025-07-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bibliography", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibliography",
            name="article_information",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bibliography",
                to="bibliography.bibliographyarticle",
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="conference_information",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bibliography",
                to="bibliography.bibliographyconference",
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="poster_information",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bibliography",
                to="bibliography.bibliographyposter",
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="software_information",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bibliography",
                to="bibliography.bibliographysoftware",
            ),
        ),
    ]
