# Generated by Django 3.2.25 on 2025-07-23 15:32

import django.db.models.deletion
from django.db import migrations, models

import metadatax.utils.custom_fields.date


class Migration(migrations.Migration):

    dependencies = [
        ("bibliography", "0004_update_bibliography_conference_information_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibliography",
            name="article_information",
            field=models.OneToOneField(
                blank=True,
                help_text="Each information is dedicated to one file.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bibliography",
                to="bibliography.bibliographyarticle",
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="poster_information",
            field=models.OneToOneField(
                blank=True,
                help_text="Each information is dedicated to one file.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bibliography",
                to="bibliography.bibliographyposter",
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="software_information",
            field=models.OneToOneField(
                blank=True,
                help_text="Each information is dedicated to one file.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bibliography",
                to="bibliography.bibliographysoftware",
            ),
        ),
        migrations.AlterField(
            model_name="bibliography",
            name="publication_date",
            field=metadatax.utils.custom_fields.date.DateField(
                blank=True,
                help_text="Required for any published bibliography",
                null=True,
            ),
        ),
    ]
