# Generated by Django 3.2.25 on 2025-12-01 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_refacto_common'),
        ('bibliography', '0005_clean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='common.person'),
        ),
        migrations.RenameField(
            model_name='author',
            old_name='contact',
            new_name='person',
        ),
    ]
