# Generated by Django 3.2.25 on 2025-12-01 15:16
from django.db import migrations, models


def migrate_biblio(apps, _):
    biblio_model = apps.get_model("bibliography", "Bibliography")

    for b in biblio_model.objects.all():
        if b.type == "A":
            b.journal = b.article_information.journal
            b.volumes = b.article_information.volumes
            b.pages_from = b.article_information.pages_from
            b.pages_to = b.article_information.pages_to
            b.issue_nb = b.article_information.issue_nb
            b.article_nb = b.article_information.article_nb
        elif b.type == "S":
            b.publication_place = b.software_information.publication_place
            b.repository_url = b.software_information.repository_url
        elif b.type == "C":
            b.conference_name = b.conference_information.conference_name
            b.conference_location = b.conference_information.conference_location
            b.conference_abstract_book_url = b.conference_information.conference_abstract_book_url
        elif b.type == "P":
            b.conference_name = b.conference_information.conference_name
            b.conference_location = b.conference_information.conference_location
            b.conference_abstract_book_url = b.conference_information.conference_abstract_book_url
            b.poster_url = b.poster_information.poster_url
        b.save()


def reverse_migrate_biblio(apps, _):
    biblio_model = apps.get_model("bibliography", "Bibliography")
    article_model = apps.get_model("bibliography", "BibliographyArticle")
    software_model = apps.get_model("bibliography", "BibliographySoftware")
    conference_model = apps.get_model("bibliography", "BibliographyConference")
    poster_model = apps.get_model("bibliography", "BibliographyPoster")

    for b in biblio_model.objects.all():
        if b.type == "A":
            c, _ = article_model.objects.get_or_create(
                journal=b.journal,
                volumes=b.volumes,
                pages_from=b.pages_from,
                pages_to=b.pages_to,
                issue_nb=b.issue_nb,
                article_nb=b.article_nb,
            )
            b.article_information = c
        elif b.type == "S":
            c, _ = software_model.objects.get_or_create(
                publication_place=b.publication_place,
                repository_url=b.repository_url,
            )
            b.software_information = c
        elif b.type == "C":
            c, _ = conference_model.objects.get_or_create(
                conference_name=b.conference_name,
                conference_location=b.conference_location,
                conference_abstract_book_url=b.conference_abstract_book_url,
            )
            b.conference_information = c
        elif b.type == "P":
            c, _ = conference_model.objects.get_or_create(
                conference_name=b.conference_name,
                conference_location=b.conference_location,
                conference_abstract_book_url=b.conference_abstract_book_url,
            )
            b.conference_information = c
            p, _ = poster_model.objects.get_or_create(
                poster_url=b.poster_url,
            )
            b.poster_information = p
        b.save()


def migrate_tags(apps, _):
    old_tag_model = apps.get_model("bibliography", "Tag")
    tag_model = apps.get_model("common", "Tag")
    tagged_item_model = apps.get_model("common", "TaggedItem")
    ct_model = apps.get_model("contenttypes", "ContentType")

    new_tags = []
    new_items = []
    biblio_ct = ct_model.objects.get(
        app_label='bibliography',
        model='bibliography',
    )
    for t in old_tag_model.objects.all():
        new_t = tag_model(name=t.name)
        new_tags.append(new_t)
        for b in t.bibliography_set.all():
            new_items.append(
                tagged_item_model(
                    tag=new_t,
                    item_type=biblio_ct,
                    item_id=b.id
                )
            )
    tag_model.objects.bulk_create(new_tags)
    tagged_item_model.objects.bulk_create(new_items)


def reverse_migrate_tags(apps, _):
    old_tag_model = apps.get_model("bibliography", "Tag")
    tagged_item_model = apps.get_model("common", "TaggedItem")
    ct_model = apps.get_model("contenttypes", "ContentType")

    biblio_ct = ct_model.objects.get(
        app_label='bibliography',
        model='bibliography',
    )
    for item in tagged_item_model.objects.filter(item_type=biblio_ct):
        old_t, _ = old_tag_model.objects.get_or_create(name=item.name)
        old_t.bibliography_set.add(item.item)


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0009_tag'),
        ('bibliography', '0006_alter_author_contact'),
    ]

    operations = [
        # Update table
        migrations.AlterModelTable(
            name='author',
            table='mx_bibliography_author',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['order', 'person__last_name']},
        ),
        migrations.AlterField(
            model_name='author',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='person',
            field=models.ForeignKey(default=0, on_delete=models.deletion.CASCADE, related_name='authors',
                                    to='common.person'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='bibliography',
            table='mx_bibliography_bibliography',
        ),
        # Add fields
        migrations.AddField(
            model_name='bibliography',
            name='article_nb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='conference_abstract_book_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='conference_location',
            field=models.CharField(blank=True, help_text='format: {City}, {Country}', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='conference_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='issue_nb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='journal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='pages_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='pages_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='publication_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='repository_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bibliography',
            name='volumes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),

        # Create proxies
        migrations.CreateModel(
            name='Article',
            fields=[
            ],
            options={
                'proxy': True,
                'constraints': [],
                'indexes': [],
            },
            bases=('bibliography.bibliography',),
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
            ],
            options={
                'proxy': True,
                'constraints': [],
                'indexes': [],
            },
            bases=('bibliography.bibliography',),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
            ],
            options={
                'proxy': True,
                'constraints': [],
                'indexes': [],
            },
            bases=('bibliography.bibliography',),
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
            ],
            options={
                'proxy': True,
                'constraints': [],
                'indexes': [],
            },
            bases=('bibliography.conference',),
        ),
        # Migrate
        migrations.RunPython(migrate_biblio, reverse_migrate_biblio),
        migrations.RunPython(migrate_tags, reverse_migrate_tags),

        # Remove fields
        migrations.RemoveConstraint(
            model_name='bibliography',
            name='Article has required information',
        ),
        migrations.RemoveField(
            model_name='bibliography',
            name='article_information',
        ),
        migrations.DeleteModel(
            name='BibliographyArticle',
        ),
        migrations.RemoveConstraint(
            model_name='bibliography',
            name='Software has required information',
        ),
        migrations.RemoveField(
            model_name='bibliography',
            name='software_information',
        ),
        migrations.DeleteModel(
            name='BibliographySoftware',
        ),
        migrations.RemoveConstraint(
            model_name='bibliography',
            name='Poster has required information',
        ),
        migrations.RemoveField(
            model_name='bibliography',
            name='poster_information',
        ),
        migrations.DeleteModel(
            name='BibliographyPoster',
        ),
        migrations.RemoveConstraint(
            model_name='bibliography',
            name='Conference has required information',
        ),
        migrations.RemoveField(
            model_name='bibliography',
            name='conference_information',
        ),
        migrations.DeleteModel(
            name='BibliographyConference',
        ),
        migrations.RemoveField(
            model_name='bibliography',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
