# Generated by Django 3.2.25 on 2025-07-16 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_add_institution_to_contact_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["last_name", "first_name"]},
        ),
    ]
