# Generated by Django 3.2.25 on 2025-07-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_contact_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactrole",
            options={"ordering": ("role", "contact", "institution")},
        ),
        migrations.AlterModelOptions(
            name="institution",
            options={"ordering": ("name",)},
        ),
    ]
