# Generated by Django 3.2.25 on 2025-12-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_clean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
