# Generated by Django 3.2.25 on 2025-12-04 12:11

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('metadatax', '0025_migrate_database'),
        ('acquisition', '0005_clean'),
        ('common', '0007_institution_make_city_country_optional'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  to='common.institution')),
            ],
            options={
                'db_table': 'mx_common_team',
                'unique_together': {('name', 'institution')},
            },
        ),
        migrations.CreateModel(
            name='PersonInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_relations',
                                   to='common.institution')),
                ('person',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_relations',
                                   to='common.contact')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='contact_relations', to='common.team')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mx_common_personinstitution',
                'unique_together': {('person', 'institution', 'team')},
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='institutions',
            field=models.ManyToManyField(related_name='persons', through='common.PersonInstitution',
                                         to='common.Institution'),
        ),
        migrations.RunSQL(
            sql="INSERT INTO mx_common_personinstitution (id, person_id, institution_id) SELECT id, contact_id, institution_id FROM metadatax_common_contact_current_institutions;SELECT setval('mx_common_personinstitution_id_seq', (SELECT max(id) from mx_common_personinstitution));",
            reverse_sql="INSERT INTO metadatax_common_contact_current_institutions (id, contact_id, institution_id) SELECT id, person_id, institution_id FROM mx_common_personinstitution;SELECT setval('metadatax_common_contact_current_institutions_id_seq', (SELECT max(id) from metadatax_common_contact_current_institutions));",
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='Person',
        ),
        migrations.AlterModelTable(
            name='person',
            table='mx_common_person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='current_institutions',
        ),
        migrations.RenameModel(
            old_name='PersonInstitution',
            new_name='PersonInstitutionRelation',
        ),
        migrations.AlterModelTable(
            name='institution',
            table='mx_common_institution',
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('institution',)},
        ),
        migrations.AlterField(
            model_name='team',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.institution'),
        ),
        migrations.AddField(
            model_name='person',
            name='teams',
            field=models.ManyToManyField(related_name='persons', through='common.PersonInstitutionRelation',
                                         to='common.Team'),
        ),
        migrations.RenameModel(
            old_name='ContactRole',
            new_name='ContactRelation',
        ),
        migrations.AlterModelTable(
            name='personinstitutionrelation',
            table='mx_common_personinstitutionrelation',
        ),
        migrations.AlterModelOptions(
            name='contactrelation',
            options={'ordering': ('role',)},
        ),
        migrations.RemoveConstraint(
            model_name='contactrelation',
            name='has_contact_or_institution',
        ),
        migrations.RenameField(
            model_name='contactrelation',
            old_name='contact',
            new_name='old_contact',
        ),
        migrations.AddField(
            model_name='contactrelation',
            name='contact_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrelation',
            name='contact_type',
            field=models.ForeignKey(default=1, limit_choices_to={
                'model__in': ['common.Person', 'common.Team', 'common.Institution']},
                                    on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='contactrelation',
            table='mx_common_contactrelation',
        ),
        migrations.AlterUniqueTogether(
            name='contactrelation',
            unique_together=set(),
        ),
        migrations.RunSQL(
            sql="""UPDATE mx_common_contactrelation
                   SET contact_id=institution_id,
                       contact_type_id=ct.id FROM django_content_type as ct
                   WHERE institution_id is not null AND ct.app_label='common' AND ct.model='institution';
            UPDATE mx_common_contactrelation
            SET contact_id=old_contact_id,
                contact_type_id=ct.id FROM django_content_type as ct
            WHERE old_contact_id is not null AND ct.app_label='common' AND ct.model='person';
            COMMIT;""",
            reverse_sql="\n            UPDATE mx_common_contactrelation\n            SET old_contact_id=contact_id\n            FROM django_content_type as ct\n            WHERE ct.app_label='common' AND ct.model='person' AND ct.id=contact_type_id;\n            UPDATE mx_common_contactrelation\n            SET institution_id=contact_id\n            FROM django_content_type as ct\n            WHERE ct.app_label='common' AND ct.model='institution' AND ct.id=contact_type_id;\n            ",
        ),
        migrations.RemoveField(
            model_name='contactrelation',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='contactrelation',
            name='old_contact',
        ),
    ]
