# Generated by Django 3.2.25 on 2025-12-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0008_refacto_common'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'mx_common_tag',
            },
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveBigIntegerField()),
                ('item_type', models.ForeignKey(on_delete=models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('tag',
                 models.ForeignKey(on_delete=models.deletion.CASCADE, to='common.tag', related_name='tagged_items')),
            ],
            options={
                'db_table': 'mx_common_taggeditem',
                'ordering': ('tag',),
                'unique_together': {('tag', 'item_type', 'item_id')},
            },
        ),
    ]
