# Generated by Django 3.2.25 on 2026-01-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mail',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
