# Generated by Django 4.2.29 on 2026-07-17 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("common", "0010_auto_20260127_1034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactrelation",
            name="contact_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "app_label": "common",
                    "model__in": ["person", "team", "institution"],
                },
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
    ]
