# Generated by Django 3.2.25 on 2025-07-10 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_add_institution_to_contact_role"),
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="maintainer_institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="performed_maintenances",
                to="common.institution",
            ),
        ),
    ]
