# Generated by Django 3.2.25 on 2025-11-27 15:56

import django.db.models.deletion
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models


def forward_migrate_model(apps, _):
    equipment = apps.get_model("equipment", "Equipment")
    model = apps.get_model("equipment", "EquipmentModel")
    model_spec = apps.get_model("equipment", "EquipmentModelSpecification")
    new_specs = []

    for e in equipment.objects.all():
        e.model = model.objects.get_or_create(
            name=e.model_name,
            provider=e.provider,
            battery_slots_count=e.battery_slots_count,
            battery_type=e.battery_type,
            cables=e.cables,
        )[0]
        if e.acoustic_detector_specification is not None:
            new_specs.append(
                model_spec(
                    model=e.model,
                    specification_type=ContentType.objects.get_for_model(
                        e.acoustic_detector_specification
                    ),
                    specification_id=e.acoustic_detector_specification.pk,
                )
            )
        if e.hydrophone_specification is not None:
            e.sensitivity = e.hydrophone_specification.sensitivity
            new_specs.append(
                model_spec(
                    model=e.model,
                    specification_type=ContentType.objects.get_for_model(
                        e.hydrophone_specification
                    ),
                    specification_id=e.hydrophone_specification.pk,
                )
            )
        if e.recorder_specification is not None:
            new_specs.append(
                model_spec(
                    model=e.model,
                    specification_type=ContentType.objects.get_for_model(
                        e.recorder_specification
                    ),
                    specification_id=e.recorder_specification.pk,
                )
            )
        if e.storage_specification is not None:
            new_specs.append(
                model_spec(
                    model=e.model,
                    specification_type=ContentType.objects.get_for_model(
                        e.storage_specification
                    ),
                    specification_id=e.storage_specification.pk,
                )
            )
        e.save()

    model_spec.objects.bulk_create(new_specs)


def reverse_migrate_model(apps, _):
    equipment = apps.get_model("equipment", "Equipment")

    for e in equipment.objects.all():
        e.model_name = e.model.name
        e.provider = e.model.provider
        e.battery_slots_count = e.model.battery_slots_count
        e.battery_type = e.model.battery_type
        e.cables = e.model.cables

        for spec in e.model.specification_relations:
            if spec.specification_type.model == "AcousticDetectorSpecification":
                e.acoustic_detector_specification = spec.specification
            if spec.specification_type.model == "HydrophoneSpecification":
                e.hydrophone_specification = spec.specification
                e.hydrophone_specification.sensitivity = spec.sensitivity
                e.hydrophone_specification.save()
            if spec.specification_type.model == "RecorderSpecification":
                e.recorder_specification = spec.specification
            if spec.specification_type.model == "StorageSpecification":
                e.storage_specification = spec.specification
        e.save()


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_clean"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("equipment", "0003_clean"),
    ]

    operations = [
        # Create models
        migrations.CreateModel(
            name="EquipmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("battery_slots_count", models.IntegerField(blank=True, null=True)),
                (
                    "battery_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cables", models.TextField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provided_equipments",
                        to="common.institution",
                    ),
                ),
            ],
            options={
                "db_table": "metadatax_equipment_equipmentmodel",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="EquipmentModelSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specification_id", models.PositiveBigIntegerField()),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specification_relations",
                        to="equipment.equipmentmodel",
                    ),
                ),
                (
                    "specification_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": [
                                "AcousticDetectorSpecification",
                                "HydrophoneSpecification",
                                "RecorderSpecification",
                                "StorageSpecification",
                            ]
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="equipmentmodelspecification",
            index=models.Index(
                fields=["specification_type", "specification_id"],
                name="equipment_e_specifi_9cc8cb_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="equipment",
            unique_together={("serial_number",)},
        ),
        migrations.RenameField(
            model_name="equipment",
            old_name="model",
            new_name="model_name",
        ),
        migrations.AddField(
            model_name="equipment",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipments",
                to="equipment.equipmentmodel",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="sensitivity",
            field=models.FloatField(
                blank=True, help_text="Required only for hydrophones", null=True
            ),
        ),
        # Migrate
        migrations.RunPython(
            code=forward_migrate_model, reverse_code=reverse_migrate_model
        ),
        # Clean
        migrations.RemoveField(
            model_name="equipment",
            name="model_name",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="acoustic_detector_specification",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="battery_slots_count",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="battery_type",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="cables",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="hydrophone_specification",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="recorder_specification",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="storage_specification",
        ),
        migrations.AlterUniqueTogether(
            name="hydrophonespecification",
            unique_together={
                (
                    "sensitivity",
                    "directivity",
                    "operating_min_temperature",
                    "operating_max_temperature",
                    "min_bandwidth",
                    "max_bandwidth",
                    "min_dynamic_range",
                    "max_dynamic_range",
                    "min_operating_depth",
                    "max_operating_depth",
                    "noise_floor",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="recorderspecification",
            unique_together={
                (
                    "channels_count",
                    "storage_slots_count",
                    "storage_maximum_capacity",
                    "storage_type",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="storagespecification",
            unique_together={("capacity", "type")},
        ),
        migrations.AlterUniqueTogether(
            name="equipment",
            unique_together={("model", "serial_number")},
        ),
        migrations.AlterUniqueTogether(
            name="equipmentmodel",
            unique_together={("name", "provider")},
        ),
        migrations.AlterUniqueTogether(
            name="hydrophonespecification",
            unique_together={
                (
                    "directivity",
                    "operating_min_temperature",
                    "operating_max_temperature",
                    "min_bandwidth",
                    "max_bandwidth",
                    "min_dynamic_range",
                    "max_dynamic_range",
                    "min_operating_depth",
                    "max_operating_depth",
                    "noise_floor",
                )
            },
        ),
        migrations.RemoveField(
            model_name="hydrophonespecification",
            name="sensitivity",
        ),
    ]
