# Generated by Django 3.2.25 on 2026-02-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('equipment', '0004_add_model_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodelspecification',
            name='specification_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['acousticdetectorspecification', 'hydrophonespecification', 'recorderspecification', 'storagespecification']}, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
    ]
