# Generated by Django 3.2.25 on 2025-12-01 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_refacto_common'),
        ('equipment', '0004_add_model_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_maintenances', to='common.person'),
        ),
    ]
