# Generated by Django 3.2.25 on 2025-12-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_maintenance_maintainer'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='equipmentmodelspecification',
            name='equipment_e_specifi_9cc8cb_idx',
        ),
        migrations.AddIndex(
            model_name='equipmentmodelspecification',
            index=models.Index(fields=['specification_type', 'specification_id'], name='mx_equipmen_specifi_19021b_idx'),
        ),
        migrations.AlterModelTable(
            name='acousticdetectorspecification',
            table='mx_equipment_acousticdetectorspecification',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='mx_equipment_equipment',
        ),
        migrations.AlterModelTable(
            name='equipmentmodel',
            table='mx_equipment_equipmentmodel',
        ),
        migrations.AlterModelTable(
            name='equipmentmodelspecification',
            table='mx_equipment_equipmentmodel_specification',
        ),
        migrations.AlterModelTable(
            name='hydrophonespecification',
            table='mx_equipment_hydrophonespecification',
        ),
        migrations.AlterModelTable(
            name='maintenance',
            table='mx_equipment_maintenance',
        ),
        migrations.AlterModelTable(
            name='maintenancetype',
            table='mx_equipment_maintenancetype',
        ),
        migrations.AlterModelTable(
            name='platform',
            table='mx_equipment_platform',
        ),
        migrations.AlterModelTable(
            name='platformtype',
            table='mx_equipment_platformtype',
        ),
        migrations.AlterModelTable(
            name='recorderspecification',
            table='mx_equipment_recorderspecification',
        ),
        migrations.AlterModelTable(
            name='storagespecification',
            table='mx_equipment_storagespecification',
        ),
    ]
