# Generated by Django 3.2.25 on 2025-12-11 13:00
from django.db import migrations, models
import django.db.models.deletion


def migrate(apps, _):
    Platform = apps.get_model("equipment", "Platform")
    ContentType = apps.get_model("contenttypes", "ContentType")

    p: Platform
    for p in Platform.objects.all():
        p.owner_type = ContentType.objects.get_for_model(p.old_owner)
        p.owner_id = p.old_owner.id
        p.save()


def reverse_migrate(apps, _):
    Platform = apps.get_model("equipment", "Platform")

    p: Platform
    for p in Platform.objects.all():
        p.old_owner = p.owner
        p.save()


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0009_tag'),
        ('equipment', '0006_table_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='owner',
            new_name='old_owner',
        ),
        migrations.AddField(
            model_name='platform',
            name='owner_id',
            field=models.PositiveBigIntegerField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='owner_type',
            field=models.ForeignKey(null=True, blank=True, limit_choices_to={
                'model__in': ['common.Person', 'common.Team', 'common.Institution']},
                                    on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.RunPython(migrate, reverse_migrate),
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together={('owner_type', 'owner_id', 'provider', 'type', 'name')},
        ),
        migrations.AlterField(
            model_name='platform',
            name='owner_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='platform',
            name='owner_type',
            field=models.ForeignKey(limit_choices_to={
                'model__in': ['common.Person', 'common.Team', 'common.Institution']},
                on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.RemoveField(
            model_name='platform',
            name='old_owner',
        ),
    ]
