# Generated by Django 3.2.25 on 2025-12-16 14:59
from django.db import migrations, models
import django.db.models.deletion


def migrate(apps, _):
    Equipment = apps.get_model("equipment", "Equipment")
    ContentType = apps.get_model("contenttypes", "ContentType")

    e: Equipment
    for e in Equipment.objects.all():
        e.owner_type = ContentType.objects.get_for_model(e.old_owner)
        e.owner_id = e.old_owner.id
        e.save()


def reverse_migrate(apps, _):
    Equipment = apps.get_model("equipment", "Equipment")

    e: Equipment
    for e in Equipment.objects.all():
        e.old_owner = e.owner
        e.save()


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('equipment', '0007_platform_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='owner',
            new_name='old_owner',
        ),
        migrations.AddField(
            model_name='equipment',
            name='owner_id',
            field=models.PositiveBigIntegerField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='owner_type',
            field=models.ForeignKey(null=True, blank=True, limit_choices_to={
                'model__in': ['common.Person', 'common.Team', 'common.Institution']},
                                    on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.RunPython(migrate, reverse_migrate),
        migrations.AlterField(
            model_name='equipment',
            name='owner_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='owner_type',
            field=models.ForeignKey(limit_choices_to={
                'model__in': ['common.Person', 'common.Team', 'common.Institution']},
                on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='old_owner',
        ),
    ]
