# Generated by Django 3.2.25 on 2026-01-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_clean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrophonespecification',
            name='max_bandwidth',
            field=models.FloatField(blank=True, help_text='Upper limiting frequency (in Hz) within a more or less flat response of the hydrophone, pre-amplification included if applicable.', null=True),
        ),
        migrations.AlterField(
            model_name='hydrophonespecification',
            name='min_bandwidth',
            field=models.FloatField(blank=True, help_text='Lower limiting frequency (in Hz) for a more or less flat response of the hydrophone, pre-amplification included if applicable.', null=True),
        ),
    ]
