# Generated by Django 3.2.25 on 2026-01-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_tag'),
        ('equipment', '0010_auto_20260123_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provided_platforms', to='common.institution'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='owner_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='owner_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['common.Person', 'common.Team', 'common.Institution']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
    ]
