# Generated by Django 3.2.25 on 2026-02-06 09:36

import datetime
from django.db import migrations, models
import metadatax.utils.custom_fields.byte
import metadatax.utils.custom_fields.date
import metadatax.utils.custom_fields.duration


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_alter_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acousticdetectorspecification',
            name='algorithm_name',
            field=models.CharField(blank=True, help_text='Name of the algorithm used by the detector.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acousticdetectorspecification',
            name='max_frequency',
            field=models.IntegerField(blank=True, help_text='Maximum frequency of the detections (in Hertz).', null=True),
        ),
        migrations.AlterField(
            model_name='acousticdetectorspecification',
            name='min_frequency',
            field=models.IntegerField(blank=True, help_text='Minimum frequency of the detections (in Hertz).', null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the equipment.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=metadatax.utils.custom_fields.date.DateField(blank=True, help_text='Date of purchase.', null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(help_text='Serial number of the equipment.', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='battery_slots_count',
            field=models.IntegerField(blank=True, help_text='Number of battery slots', null=True),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='battery_type',
            field=models.CharField(blank=True, help_text='Type of battery supported by the model', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='cables',
            field=models.TextField(blank=True, help_text='List of cables required to use the model', null=True),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='name',
            field=models.CharField(help_text='Name of the model', max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=metadatax.utils.custom_fields.date.DateField(default=datetime.date.today, help_text='Date of the maintenance operation'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the maintenance', null=True),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this type of maintenance', null=True),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='interval',
            field=metadatax.utils.custom_fields.duration.DurationField(blank=True, help_text='Recommended interval of execution for this type of maintenance', null=True),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the maintenance type', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the platform', null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the platform', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='platformtype',
            name='is_mobile',
            field=models.BooleanField(default=False, help_text='Is this platform mobile'),
        ),
        migrations.AlterField(
            model_name='platformtype',
            name='name',
            field=models.CharField(help_text='Name of the platform', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recorderspecification',
            name='storage_maximum_capacity',
            field=metadatax.utils.custom_fields.byte.ByteField(base_field=models.CharField(max_length=4), blank=True, help_text='Maximum storage capacity supported by the recorder.', null=True, size=2),
        ),
        migrations.AlterField(
            model_name='recorderspecification',
            name='storage_slots_count',
            field=models.IntegerField(blank=True, help_text='Number of all the storage slots on the recorder.', null=True),
        ),
        migrations.AlterField(
            model_name='recorderspecification',
            name='storage_type',
            field=models.CharField(blank=True, help_text='Type of storage supported by the recorder.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='storagespecification',
            name='capacity',
            field=metadatax.utils.custom_fields.byte.ByteField(base_field=models.CharField(max_length=4), help_text='Capacity of the storage.', size=2),
        ),
        migrations.AlterField(
            model_name='storagespecification',
            name='type',
            field=models.CharField(blank=True, help_text='Type of storage.', max_length=100, null=True),
        ),
    ]
