# Generated by Django 3.2.25 on 2026-02-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipmentmodelspecification_specification_type'),
        ('equipment', '0012_help_texts'),
    ]

    operations = [
    ]
