# Generated by Django 4.2.29 on 2026-07-17 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("equipment", "0013_merge_20260211_1522"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="owner_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "app_label": "common",
                    "model__in": ["person", "team", "institution"],
                },
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="owner_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "app_label": "common",
                    "model__in": ["person", "team", "institution"],
                },
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
    ]
