# Generated by Django 4.2.29 on 2026-07-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("equipment", "0014_alter_equipment_owner_type_alter_platform_owner_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentmodelspecification",
            name="specification_type",
            field=models.ForeignKey(
                limit_choices_to={
                    "app_label": "equipment",
                    "model__in": [
                        "acousticdetectorspecification",
                        "hydrophonespecification",
                        "recorderspecification",
                        "storagespecification",
                    ],
                },
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
    ]
