# Generated by Django 4.2.29 on 2026-09-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0015_alter_equipmentmodelspecification_specification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="sensitivity",
            field=models.FloatField(
                blank=True,
                help_text="\n        Average sensitivity of the hydrophone (dB re 1V/µPa), pre-amplification included if applicable. \n        Sensitivity Sh of the hydrophone such that : data(uPa) = data(volt)*10^((-Sh-G)/20).\n        See Recorder Gain for definition of G.\n        Required only for hydrophones\n        ",
                null=True,
            ),
        ),
    ]
