from .acoustic_detector_specification import AcousticDetectorSpecificationAdmin
from .equipment import EquipmentAdmin
from .hydrophone_specification import HydrophoneSpecificationAdmin
from .platform import PlatformAdmin
from .platform_type import PlatformTypeAdmin
from .recorder_specification import RecorderSpecificationAdmin
from .sd_card_specification import SDCardSpecificationAdmin
