# Generated by Django 3.2.25 on 2025-06-30 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_alter_file_format"),
        ("equipment", "0001_initial"),
        ("common", "0002_alter_contactrole_contact"),
        ("ontology", "0001_initial"),
        ("acquisition", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deploymentmobileposition",
            options={},
        ),
        migrations.AlterField(
            model_name="channelconfiguration",
            name="detector_specification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channel_configuration",
                to="acquisition.channelconfigurationdetectorspecification",
            ),
        ),
        migrations.AlterField(
            model_name="channelconfiguration",
            name="other_equipments",
            field=models.ManyToManyField(
                blank=True,
                related_name="channel_configurations",
                to="equipment.Equipment",
            ),
        ),
        migrations.AlterField(
            model_name="channelconfiguration",
            name="recorder_specification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channel_configuration",
                to="acquisition.channelconfigurationrecorderspecification",
            ),
        ),
        migrations.AlterField(
            model_name="channelconfigurationdetectorspecification",
            name="labels",
            field=models.ManyToManyField(
                related_name="channel_configuration_detector_specifications",
                to="ontology.Label",
            ),
        ),
        migrations.AlterField(
            model_name="channelconfigurationdetectorspecification",
            name="output_formats",
            field=models.ManyToManyField(
                related_name="channel_configuration_detector_specifications",
                to="data.FileFormat",
            ),
        ),
        migrations.AlterField(
            model_name="channelconfigurationrecorderspecification",
            name="recording_formats",
            field=models.ManyToManyField(
                related_name="channel_configuration_recorder_specifications",
                to="data.FileFormat",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="contacts",
            field=models.ManyToManyField(
                help_text="Should have at least one 'Main Contact'",
                related_name="projects",
                to="common.ContactRole",
            ),
        ),
    ]
