# Generated by Django 3.2.25 on 2025-07-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibliography", "0001_initial"),
        ("acquisition", "0003_auto_20250630_1401"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="related_bibliography",
            field=models.ManyToManyField(
                related_name="related_projects", to="bibliography.Bibliography"
            ),
        ),
    ]
