# Generated by Django 3.2.25 on 2025-07-23 15:29

import django.db.models.deletion
from django.db import migrations, models

import metadatax.utils.custom_fields.date
import metadatax.utils.custom_fields.datetime


class Migration(migrations.Migration):

    dependencies = [
        ("acquisition", "0004_project_related_bibliography"),
    ]

    operations = [
        migrations.RenameField(
            model_name="channelconfiguration",
            old_name="other_equipments",
            new_name="storages",
        ),
        migrations.AlterField(
            model_name="channelconfiguration",
            name="detector_specification",
            field=models.OneToOneField(
                blank=True,
                help_text="Each specification is dedicated to one file.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channel_configuration",
                to="acquisition.channelconfigurationdetectorspecification",
            ),
        ),
        migrations.AlterField(
            model_name="channelconfiguration",
            name="recorder_specification",
            field=models.OneToOneField(
                blank=True,
                help_text="Each specification is dedicated to one file.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channel_configuration",
                to="acquisition.channelconfigurationrecorderspecification",
            ),
        ),
        migrations.AlterField(
            model_name="channelconfiguration",
            name="harvest_ending_date",
            field=metadatax.utils.custom_fields.datetime.DateTimeField(
                blank=True,
                help_text="Harvest stop date at which the channel configuration finished to record in (in UTC).",
                null=True,
                verbose_name="Harvest stop date (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="channelconfiguration",
            name="harvest_starting_date",
            field=metadatax.utils.custom_fields.datetime.DateTimeField(
                blank=True,
                help_text="Harvest start date at which the channel configuration was idle to record (in UTC).",
                null=True,
                verbose_name="Harvest start date (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="deployment_date",
            field=metadatax.utils.custom_fields.datetime.DateTimeField(
                blank=True,
                help_text="Date and time at which the measurement system was deployed in UTC.",
                null=True,
                verbose_name="Deployment date (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="recovery_date",
            field=metadatax.utils.custom_fields.datetime.DateTimeField(
                blank=True,
                help_text="Date and time at which the measurement system was recovered in UTC.",
                null=True,
                verbose_name="Recovery date (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="deploymentmobileposition",
            name="datetime",
            field=metadatax.utils.custom_fields.datetime.DateTimeField(
                help_text="Datetime for the mobile platform position"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=metadatax.utils.custom_fields.date.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=metadatax.utils.custom_fields.date.DateField(blank=True, null=True),
        ),
    ]
