# Generated by Django 3.2.25 on 2026-01-08 13:49

from django.db import migrations, models
import metadatax.utils.custom_fields.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0007_refacto'),
        ('acquisition', '0006_refacto_common'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelconfiguration',
            name='harvest_ending_date',
            field=metadatax.utils.custom_fields.datetime.DateTimeField(blank=True, help_text='Date at which the channel configuration finished to record in (in UTC).', null=True, verbose_name='Harvest stop date (UTC)'),
        ),
        migrations.AlterField(
            model_name='channelconfiguration',
            name='harvest_starting_date',
            field=metadatax.utils.custom_fields.datetime.DateTimeField(blank=True, help_text='Date at which the channel configuration started to record (in UTC).', null=True, verbose_name='Harvest start date (UTC)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='related_bibliography',
            field=models.ManyToManyField(blank=True, related_name='related_projects', to='bibliography.Bibliography'),
        ),
        migrations.AlterModelTable(
            name='campaign',
            table='mx_acquisition_campaign',
        ),
        migrations.AlterModelTable(
            name='channelconfiguration',
            table='mx_acquisition_channelconfiguration',
        ),
        migrations.AlterModelTable(
            name='channelconfigurationdetectorspecification',
            table='mx_acquisition_channelconfigurationdetectorspecification',
        ),
        migrations.AlterModelTable(
            name='channelconfigurationfiles',
            table='mx_acquisition_channelconfigurationfiles',
        ),
        migrations.AlterModelTable(
            name='channelconfigurationrecorderspecification',
            table='mx_acquisition_channelconfigurationrecorderspecification',
        ),
        migrations.AlterModelTable(
            name='deployment',
            table='mx_acquisition_deployment',
        ),
        migrations.AlterModelTable(
            name='deploymentmobileposition',
            table='mx_acquisition_deploymentmobileposition',
        ),
        migrations.AlterModelTable(
            name='project',
            table='mx_acquisition_project',
        ),
        migrations.AlterModelTable(
            name='projecttype',
            table='mx_acquisition_projecttype',
        ),
        migrations.AlterModelTable(
            name='site',
            table='mx_acquisition_site',
        ),
    ]
