# Generated by Django 3.2.25 on 2026-01-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0007_auto_20260108_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelconfigurationrecorderspecification',
            name='channel_name',
            field=models.CharField(blank=True, help_text='Name of the channel used for recording.', max_length=5, null=True),
        ),
    ]
