# Generated by Django 3.2.25 on 2026-01-29 08:51

from django.db import migrations
import metadatax.utils.custom_fields.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0008_alter_channelconfigurationrecorderspecification_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelconfiguration',
            name='record_end_date',
            field=metadatax.utils.custom_fields.datetime.DateTimeField(blank=True, help_text='Date at which the channel configuration finished to record in (in UTC).', null=True, verbose_name='Harvest stop date (UTC)'),
        ),
        migrations.AddField(
            model_name='channelconfiguration',
            name='record_start_date',
            field=metadatax.utils.custom_fields.datetime.DateTimeField(blank=True, help_text='Date at which the channel configuration started to record (in UTC).', null=True, verbose_name='Harvest start date (UTC)'),
        ),
        migrations.AlterField(
            model_name='channelconfiguration',
            name='harvest_ending_date',
            field=metadatax.utils.custom_fields.datetime.DateTimeField(blank=True, help_text='Harvest stop date at which the channel configuration was stopped (in UTC).', null=True, verbose_name='Harvest stop date (UTC)'),
        ),
        migrations.AlterField(
            model_name='channelconfiguration',
            name='harvest_starting_date',
            field=metadatax.utils.custom_fields.datetime.DateTimeField(blank=True, help_text='Harvest start date at which the channel configuration was idle to record (in UTC).', null=True, verbose_name='Harvest start date (UTC)'),
        ),
    ]
