# Generated by Django 3.2.25 on 2026-01-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0009_channel_configuration_record_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelconfiguration',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('F', 'Failed'), ('L', 'Lost')], default='A', max_length=1, null=True),
        ),
    ]
