# Generated by Django 3.2.25 on 2026-02-06 08:06

from django.db import migrations

import metadatax


class Migration(migrations.Migration):
    dependencies = [
        ('acquisition', '0010_channelconfiguration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelconfiguration',
            name='record_end_date',
        ),
        migrations.RemoveField(
            model_name='channelconfiguration',
            name='record_start_date',
        ),
        migrations.RenameField(
            model_name='channelconfiguration',
            old_name='harvest_ending_date',
            new_name='record_end_date',
        ),
        migrations.RenameField(
            model_name='channelconfiguration',
            old_name='harvest_starting_date',
            new_name='record_start_date',
        ),
        migrations.AlterField(
            model_name='channelconfiguration',
            name='record_end_date',
            field=metadatax.utils.custom_fields.datetime.DateTimeField(blank=True,
                                                                       help_text='Date at which the channel configuration finished to record in (in UTC).',
                                                                       null=True,
                                                                       verbose_name='Record stop date (UTC)'),
        ),
        migrations.AlterField(
            model_name='channelconfiguration',
            name='record_start_date',
            field=metadatax.utils.custom_fields.datetime.DateTimeField(blank=True,
                                                                       help_text='Date at which the channel configuration started to record (in UTC).',
                                                                       null=True,
                                                                       verbose_name='Record start date (UTC)'),
        ),
    ]
