# Generated by Django 3.2.25 on 2026-02-06 09:35

from django.db import migrations, models
import metadatax.utils.custom_fields.date


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0011_auto_20260206_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelconfiguration',
            name='timezone',
            field=models.CharField(blank=True, help_text='Timezone of the recording.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='channelconfigurationdetectorspecification',
            name='configuration',
            field=models.TextField(blank=True, help_text='Description of the configuration', null=True),
        ),
        migrations.AlterField(
            model_name='channelconfigurationdetectorspecification',
            name='filter',
            field=models.TextField(blank=True, help_text='Filter applied to the configuration', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=metadatax.utils.custom_fields.date.DateField(blank=True, help_text='End date of the project', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=metadatax.utils.custom_fields.date.DateField(blank=True, help_text='Start date of the project', null=True),
        ),
    ]
