# Generated by Django 3.2.25 on 2026-02-10 13:49

from django.db import migrations, models
import django.db.models.deletion
import metadatax.acquisition.models.channel_configuration_specifications.recorder_specification


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_help_texts'),
        ('acquisition', '0012_help_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelconfiguration',
            name='timezone',
            field=models.CharField(blank=True, help_text='Timezone of the recording (ISO format, eg: +00:00).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='channelconfigurationrecorderspecification',
            name='hydrophone',
            field=models.ForeignKey(help_text='If the hydrophone is integrated into the recorder, select it as hydrophone as well.', on_delete=django.db.models.deletion.PROTECT, related_name='channel_configuration_hydrophone_specifications', to='equipment.equipment', validators=[metadatax.acquisition.models.channel_configuration_specifications.recorder_specification.validate_hydrophone]),
        ),
    ]
