# Generated by Django 3.2.25 on 2026-02-26 08:57

from django.db import migrations, models


def migrate(apps, _):
    ChannelConfiguration = apps.get_model("acquisition", "ChannelConfiguration")
    ChannelConfiguration.objects.filter(status="L").update(is_lost=True)


def reverse_migration(apps, _):
    ChannelConfiguration = apps.get_model("acquisition", "ChannelConfiguration")
    ChannelConfiguration.objects.filter(is_lost=True).update(status="L")


class Migration(migrations.Migration):
    dependencies = [
        ('acquisition', '0013_auto_20260210_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelconfiguration',
            name='is_lost',
            field=models.BooleanField(default=False, help_text='If the equipment is lost.'),
        ),
        migrations.RunPython(migrate, reverse_migration),
    ]
