# Generated by Django 3.2.25 on 2026-02-26 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('acquisition', '0014_channelconfiguration_status_to_islost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelconfiguration',
            name='status',
        ),
    ]
