# Generated by Django 4.2.29 on 2026-09-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0008_alter_visualobservation_behaviors_and_more"),
        ("acquisition", "0015_channelconfiguration_status_to_islost_clean"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelconfigurationrecorderspecification",
            name="gain",
            field=models.FloatField(
                blank=True,
                help_text="Gain of the channel (recorder), with correction factors if applicable, without hydrophone sensibility (in dB). If end-to-end calibration with hydrophone sensibility, set it in Sensitivity and set Gain to 0 dB.<br>Gain G of the channel such that : data(uPa) = data(volt)*10^((-Sh-G)/20). See Sensitivity for Sh definition.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="channelconfigurationrecorderspecification",
            name="recording_formats",
            field=models.ManyToManyField(
                blank=True,
                related_name="channel_configuration_recorder_specifications",
                to="data.fileformat",
            ),
        ),
    ]
