# Generated by Django 3.2.25 on 2025-06-24 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("metadatax_common", "0001_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Description of the type of the project",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the project", max_length=255, unique=True
                    ),
                ),
                (
                    "accessibility",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("C", "Confidential"),
                            ("R", "Upon request"),
                            ("O", "Open access"),
                        ],
                        help_text="Accessibility level of the data. If the availability is not sure or non-uniform within the project, the default value is upon request.",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier of the data, if existing.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "project_goal",
                    models.TextField(
                        blank=True,
                        help_text="Description of the goal of the project.",
                        null=True,
                    ),
                ),
                (
                    "financing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PU", "Public"),
                            ("PR", "Private"),
                            ("MI", "Mixte"),
                            ("NF", "Not Financed"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "contacts",
                    models.ManyToManyField(
                        help_text="Should have at least one 'Main Contact'",
                        to="metadatax_common.ContactRole",
                    ),
                ),
                (
                    "project_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Description of the type of the project (e.g., research, marine renewable energies, long monitoring,...).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="metadatax_acquisition.projecttype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
