# Generated by Django 3.2.25 on 2025-06-24 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("metadatax_acquisition", "0001_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the platform conceptual location. A site may group together several platforms in relatively close proximity, or describes a location where regular deployments are carried out.",
                        max_length=255,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project associated to this site",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="metadatax_acquisition.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "name"],
                "unique_together": {("name", "project")},
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the campaign during which the instrument was deployed.",
                        max_length=255,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project associated to this campaign",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="metadatax_acquisition.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "name"],
                "unique_together": {("name", "project")},
            },
        ),
    ]
