# Generated by Django 5.0.4 on 2024-04-09 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("bathymetric_depth", models.IntegerField(blank=True, null=True)),
                ("deployment_date", models.DateTimeField(blank=True, null=True)),
                ("recovery_date", models.DateTimeField(blank=True, null=True)),
                (
                    "deployment_vessel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recovery_vessel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("campaign", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "platform_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("platform_type", models.TextField()),
                ("platform_description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hydrophone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=255, null=True)),
                ("model", models.CharField(max_length=255)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sensitivity", models.FloatField()),
                (
                    "directivity",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("OMNI", "Omni-directional"),
                            ("BI", "Bi-directional"),
                            ("UNI", "Uni-directional"),
                        ],
                        null=True,
                    ),
                ),
                ("bandwidth", models.FloatField(blank=True, null=True)),
                ("noise_floor", models.FloatField(blank=True, null=True)),
                ("dynamic_range", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("number_of_channels", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChannelConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_name", models.CharField(blank=True, max_length=5, null=True)),
                ("continuous", models.BooleanField(blank=True, null=True)),
                ("duty_cycle_on", models.IntegerField(blank=True, null=True)),
                ("duty_cycle_off", models.IntegerField(blank=True, null=True)),
                ("sampling_frequency", models.IntegerField()),
                ("gain", models.IntegerField()),
                ("sample_depth", models.IntegerField()),
                ("hydrophone_depth", models.IntegerField(blank=True, null=True)),
                ("recording_format", models.TextField(blank=True, null=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metadatax.deployment",
                    ),
                ),
                (
                    "hydrophone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metadatax.hydrophone",
                    ),
                ),
                (
                    "recorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metadatax.recorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("initial_timestamp", models.DateTimeField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("storage_location", models.TextField(blank=True, null=True)),
                ("sampling_frequency", models.IntegerField()),
                ("sample_depth", models.IntegerField(blank=True, null=True)),
                ("bit_counts", models.IntegerField(blank=True, null=True)),
                ("format", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "accessibility",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("C", "Confidential"),
                            ("R", "Upon request"),
                            ("O", "Open access"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "channel_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metadatax.channelconfiguration",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deployment",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="metadatax.institution"
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "accessibility",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("C", "Confidential"),
                            ("R", "Upon request"),
                            ("O", "Open access"),
                        ],
                        null=True,
                    ),
                ),
                ("doi", models.CharField(blank=True, max_length=255, null=True)),
                ("project_type", models.TextField(blank=True, null=True)),
                ("project_goal", models.TextField(blank=True, null=True)),
                (
                    "responsible_parties",
                    models.ManyToManyField(
                        related_name="projects", to="metadatax.institution"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deployment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="metadatax.project"
            ),
        ),
    ]
