# Generated by Django 5.0.4 on 2024-04-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadatax", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hydrophone",
            name="max_operating_depth",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hydrophone",
            name="operating_max_temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hydrophone",
            name="operating_min_temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hydrophone",
            name="directivity",
            field=models.TextField(
                blank=True,
                choices=[
                    ("OMNI", "Omni-directional"),
                    ("BI", "Bi-directional"),
                    ("UNI", "Uni-directional"),
                    ("CAR", "Cardioid"),
                    ("SCAR", "Supercardioid"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hydrophone",
            name="provider",
            field=models.CharField(max_length=255),
        ),
    ]
