# Generated by Django 5.0.4 on 2024-04-10 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadatax", "0002_attributes_v2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deployments",
                to="metadatax.project",
            ),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="metadatax.institution",
            ),
        ),
    ]
