# Generated by Django 5.0.4 on 2024-04-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadatax", "0003_alter_deployment_project_alter_deployment_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelconfiguration",
            name="recording_format",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="hydrophone",
            unique_together={("provider", "model", "serial_number")},
        ),
        migrations.AlterUniqueTogether(
            name="recorder",
            unique_together={("provider", "model", "serial_number")},
        ),
    ]
