# Generated by Django 5.0.4 on 2024-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadatax", "0004_alter_channelconfiguration_recording_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="bit_counts",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
