# Generated by Django 5.0.4 on 2024-04-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadatax", "0005_alter_file_bit_counts"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="file",
            unique_together={("channel_configuration", "name")},
        ),
    ]
