# Generated by Django 3.2.25 on 2024-05-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadatax', '0006_alter_file_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='metadatax.institution'),
        ),
    ]
