# Generated by Django 3.2.25 on 2024-05-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadatax', '0009_auto_20240523_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
