# Generated by Django 3.2.25 on 2024-05-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadatax', '0010_alter_deployment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrophone',
            name='serial_number',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recorder',
            name='serial_number',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
    ]
