# Generated by Django 3.2.25 on 2024-05-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadatax", "0011_auto_20240523_1143"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hydrophonemodel",
            options={
                "ordering": ["provider", "name"],
                "verbose_name": "Equipment - Hydrophone - Model",
            },
        ),
        migrations.AlterModelOptions(
            name="recordermodel",
            options={
                "ordering": ["provider", "name"],
                "verbose_name": "Equipment - Recorder - Model",
            },
        ),
    ]
