# Generated by Django 3.2.25 on 2024-05-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadatax', '0013_auto_20240523_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['project', 'name'], 'verbose_name': 'Project - Campaign'},
        ),
        migrations.AlterModelOptions(
            name='channelconfiguration',
            options={'ordering': ['deployment', 'channel_name']},
        ),
        migrations.AlterModelOptions(
            name='deployment',
            options={'ordering': ['project', 'name']},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['name'], 'verbose_name': 'Deployment - Platform'},
        ),
        migrations.AlterModelOptions(
            name='platformtype',
            options={'ordering': ['name'], 'verbose_name': 'Deployment - Platform - Type'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='projecttype',
            options={'ordering': ['name'], 'verbose_name': 'Project - Type'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['project', 'name'], 'verbose_name': 'Project - Site'},
        ),
        migrations.AlterField(
            model_name='channelconfiguration',
            name='gain',
            field=models.FloatField(),
        ),
    ]
