# Generated by Django 3.2.25 on 2024-05-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadatax', '0007_alter_deployment_provider'),
        ('metadatax', '0013_auto_20240523_1155'),
    ]

    operations = [
    ]
