# Generated by Django 3.2.25 on 2024-05-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadatax', '0014_merge_20240523_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelconfiguration',
            name='gain',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='metadatax.institution'),
        ),
    ]
