# Generated by Django 3.2.25 on 2024-05-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadatax', '0015_auto_20240523_1655'),
        ('metadatax', '0016_auto_20240523_1639'),
    ]

    operations = [
    ]
