# Generated by Django 3.2.25 on 2024-05-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadatax', '0017_auto_20240527_0943'),
        ('metadatax', '0019_auto_20240527_1404'),
    ]

    operations = [
    ]
