# Generated by Django 3.2.25 on 2024-06-10 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadatax", "0020_alter_recorder_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployment",
            name="deployment_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2020, 1, 1, 12, 0),
                help_text="Date and time at which the measurement system was deployed in UTC.",
                null=True,
                verbose_name="Deployment date (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="recovery_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2020, 1, 1, 12, 0),
                help_text="Date and time at which the measurement system was recovered in UTC.",
                null=True,
                verbose_name="Recovery date (UTC)",
            ),
        ),
    ]
