# Generated by Django 3.2.25 on 2024-09-11 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadatax", "0021_auto_20240610_0851"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelconfiguration",
            name="duty_cycle_off",
            field=models.IntegerField(
                blank=True,
                help_text="If it's not Continuous, time length (in second) during which the recorder is off.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="channelconfiguration",
            name="duty_cycle_on",
            field=models.IntegerField(
                blank=True,
                help_text="If it's not Continuous, time length (in second) during which the recorder is on.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
