# Generated by Django 3.2.25 on 2025-01-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadatax", "0022_auto_20240911_1902"),
    ]

    operations = [
        migrations.AddField(
            model_name="recorder",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name of the recorder", max_length=255, null=True
            ),
        ),
    ]
