# Generated by Django 3.2.25 on 2025-01-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadatax", "0023_auto_20250117_1418"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformtype",
            name="type",
            field=models.TextField(
                blank=True,
                choices=[("F", "Fix"), ("M", "Mobile")],
                default="F",
                help_text="Whether the platform is fix or mobile",
                null=True,
            ),
        ),
    ]
