# Generated by Django 3.2.25 on 2025-03-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadatax', '0023_auto_20250117_1057'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mobileplatform',
            constraint=models.UniqueConstraint(fields=('deployment', 'datetime'), name='unique_position_at_datetime_for_deployment'),
        ),
    ]
