# Generated by Django 3.2.25 on 2024-09-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadatax', '0023_auto_20240926_1019'),
        ('metadatax', '0023_merge_0022_auto_20240911_1902_0022_auto_20240913_1030'),
    ]

    operations = [
    ]
