# Generated by Django 3.2.25 on 2025-06-25 09:10

from django.db import migrations

from metadatax_common.models import ContactRole


class MigrationAction:
    def __init__(self, apps, _):
        self.unknown_format_id = None
        self.apps = apps

        self.Contact = apps.get_model("metadatax_common", "Contact")
        self.ContactRole = apps.get_model("metadatax_common", "ContactRole")
        self.migration_contact, _ = self.Contact.objects.get_or_create(
            name="[Migration]"
        )

        self.ProjectType = apps.get_model("metadatax_acquisition", "ProjectType")
        self.Project = apps.get_model("metadatax_acquisition", "Project")
        self.ProjectContactThrough = self.Project.contacts.through
        self.Site = apps.get_model("metadatax_acquisition", "Site")
        self.Campaign = apps.get_model("metadatax_acquisition", "Campaign")
        self.Deployment = apps.get_model("metadatax_acquisition", "Deployment")
        self.DeploymentContactThrough = self.Deployment.contacts.through
        self.ChannelConfiguration = apps.get_model(
            "metadatax_acquisition", "ChannelConfiguration"
        )
        self.ChannelConfigurationRecorderSpecification = apps.get_model(
            "metadatax_acquisition", "ChannelConfigurationRecorderSpecification"
        )
        self.ChannelConfigurationRecorderSpecificationFormatThrough = (
            self.ChannelConfigurationRecorderSpecification.recording_formats.through
        )
        self.DeploymentMobilePosition = apps.get_model(
            "metadatax_acquisition", "DeploymentMobilePosition"
        )
        self.ChannelConfigurationFiles = apps.get_model(
            "metadatax_acquisition", "ChannelConfigurationFiles"
        )

        self.PlatformType = apps.get_model("metadatax_equipment", "PlatformType")
        self.Platform = apps.get_model("metadatax_equipment", "Platform")
        self.Equipment = apps.get_model("metadatax_equipment", "Equipment")
        self.RecorderSpecification = apps.get_model(
            "metadatax_equipment", "RecorderSpecification"
        )
        self.HydrophoneSpecification = apps.get_model(
            "metadatax_equipment", "HydrophoneSpecification"
        )

        self.FileFormat = apps.get_model("metadatax_data", "FileFormat")
        self.File = apps.get_model("metadatax_data", "File")
        self.AudioProperties = apps.get_model("metadatax_data", "AudioProperties")

        self.run_migration(apps.get_model("metadatax", "Project").objects.all())

    def run_migration(self, old_projects):
        self.migrate_projects(old_projects=old_projects)
        self.migrate_project_types(old_projects=old_projects)
        self.migrate_sites(old_projects=old_projects)
        self.migrate_campaigns(old_projects=old_projects)
        self.migrate_platforms(old_projects=old_projects)
        self.migrate_platform_types(old_projects=old_projects)
        self.migrate_deployments(old_projects=old_projects)
        self.migrate_channel_configurations(old_projects=old_projects)
        self.migrate_file_formats(old_projects=old_projects)
        self.migrate_equipment(old_projects=old_projects)
        self.migrate_recorder_specifications(old_projects=old_projects)
        self.migrate_hydrophone_specifications(old_projects=old_projects)
        self.migrate_channel_configuration_recorder_specification(
            old_projects=old_projects
        )
        self.migrate_channel_configuration_recorder_specifications_format_through(
            old_projects=old_projects
        )
        self.migrate_contacts(old_projects=old_projects)
        self.migrate_contact_roles(old_projects=old_projects)
        self.migrate_project_contact_roles(old_projects=old_projects)
        self.migrate_deployment_contact_roles(old_projects=old_projects)
        self.migrate_deployment_mobile_positions(old_projects=old_projects)
        self.migrate_files(old_projects=old_projects)
        self.migrate_audio_properties(old_projects=old_projects)
        self.migrate_channel_configuration_files(old_projects=old_projects)

    def migrate_projects(self, old_projects):
        self.Project.objects.bulk_create(
            [
                self.Project(
                    id=project.id,
                    name=project.name,
                    accessibility=project.accessibility,
                    doi=project.doi,
                    project_type_id=project.project_type_id,
                    project_goal=project.project_goal,
                )
                for project in old_projects
            ]
        )

    def migrate_project_types(self, old_projects):
        self.ProjectType.objects.bulk_create(
            [
                self.ProjectType(
                    id=project.project_type.id,
                    name=project.project_type.name,
                )
                for project in old_projects
                if project.project_type is not None
            ],
            ignore_conflicts=True,
        )

    def migrate_sites(self, old_projects):
        self.Site.objects.bulk_create(
            [
                self.Site(id=site.id, name=site.name, project_id=project.id)
                for project in old_projects
                for site in project.sites.all()
            ],
            ignore_conflicts=True,
        )

    def migrate_campaigns(self, old_projects):
        self.Campaign.objects.bulk_create(
            [
                self.Campaign(id=campaign.id, name=campaign.name, project_id=project.id)
                for project in old_projects
                for campaign in project.campaigns.all()
            ],
            ignore_conflicts=True,
        )

    def migrate_deployments(self, old_projects):
        self.Deployment.objects.bulk_create(
            [
                self.Deployment(
                    id=deployment.id,
                    project_id=project.id,
                    longitude=deployment.longitude,
                    latitude=deployment.latitude,
                    name=deployment.name,
                    bathymetric_depth=deployment.bathymetric_depth,
                    deployment_date=deployment.deployment_date,
                    deployment_vessel=deployment.deployment_vessel,
                    recovery_date=deployment.recovery_date,
                    recovery_vessel=deployment.recovery_vessel,
                    description=deployment.description,
                    site_id=deployment.site_id,
                    campaign_id=deployment.campaign_id,
                    platform_id=deployment.platform_id,
                )
                for project in old_projects
                for deployment in project.deployments.all()
            ]
        )

    def migrate_platforms(self, old_projects):
        self.Platform.objects.bulk_create(
            [
                self.Platform(
                    id=deployment.platform_id,
                    owner=self.migration_contact,
                    provider=self.migration_contact,
                    type_id=deployment.platform.type_id,
                    name=deployment.platform.name,
                    description=deployment.platform.description,
                )
                for project in old_projects
                for deployment in project.deployments.all()
                if deployment.platform is not None
            ],
            ignore_conflicts=True,
        )

    def migrate_platform_types(self, old_projects):
        self.PlatformType.objects.bulk_create(
            [
                self.PlatformType(
                    id=deployment.platform.type.id,
                    name=deployment.platform.type.name,
                    is_mobile=deployment.platform.type.type == "M",
                )
                for project in old_projects
                for deployment in project.deployments.all()
                if deployment.platform_id is not None
            ],
            ignore_conflicts=True,
        )

    def migrate_channel_configurations(self, old_projects):
        self.ChannelConfiguration.objects.bulk_create(
            [
                self.ChannelConfiguration(
                    id=channel.id,
                    deployment_id=deployment.id,
                    recorder_specification_id=channel.id,
                    continuous=channel.continuous,
                    duty_cycle_on=channel.duty_cycle_on,
                    duty_cycle_off=channel.duty_cycle_off,
                    instrument_depth=channel.hydrophone_depth,
                    harvest_starting_date=channel.harvest_starting_date,
                    harvest_ending_date=channel.harvest_ending_date,
                )
                for project in old_projects
                for deployment in project.deployments.all()
                for channel in deployment.channelconfiguration_set.all()
            ]
        )

    def migrate_channel_configuration_recorder_specification(self, old_projects):
        self.ChannelConfigurationRecorderSpecification.objects.bulk_create(
            [
                self.ChannelConfigurationRecorderSpecification(
                    id=channel.id,
                    recorder_id=channel.recorder_id,
                    hydrophone=self.Equipment.objects.get(
                        provider__name=channel.hydrophone.model.provider.name,
                        model=channel.hydrophone.model.name,
                        serial_number=channel.hydrophone.serial_number,
                    ),
                    sampling_frequency=channel.sampling_frequency,
                    sample_depth=channel.sample_depth,
                    gain=channel.gain,
                    channel_name=channel.channel_name,
                )
                for project in old_projects
                for deployment in project.deployments.all()
                for channel in deployment.channelconfiguration_set.all()
            ]
        )

    def migrate_channel_configuration_recorder_specifications_format_through(
        self, old_projects
    ):
        self.ChannelConfigurationRecorderSpecificationFormatThrough.objects.bulk_create(
            [
                self.ChannelConfigurationRecorderSpecificationFormatThrough(
                    channelconfigurationrecorderspecification_id=channel.id,
                    fileformat_id=channel.recording_format_id,
                )
                for project in old_projects
                for deployment in project.deployments.all()
                for channel in deployment.channelconfiguration_set.all()
            ]
        )

    def migrate_contacts(self, old_projects):
        self.Contact.objects.bulk_create(
            list(
                set(
                    [
                        self.Contact(
                            id=institution.id,
                            name=institution.name,
                            mail=institution.contact,
                            website=institution.website,
                        )
                        for institution in [
                            *[
                                institution
                                for project in old_projects
                                for institution in project.responsible_parties.all()
                            ],
                            *[
                                deployment.provider
                                for project in old_projects
                                for deployment in project.deployments.all()
                                if deployment.provider is not None
                            ],
                        ]
                    ]
                )
            ),
            ignore_conflicts=True,
        )

    def migrate_contact_roles(self, old_projects):
        self.ContactRole.objects.bulk_create(
            [
                *[
                    self.ContactRole(
                        id=institution.id,
                        contact_id=institution.id,
                        role=ContactRole.Type.MAIN_CONTACT,
                    )
                    for project in old_projects
                    for institution in project.responsible_parties.all()
                ],
                *[
                    self.ContactRole(
                        id=deployment.provider.id,
                        contact_id=deployment.provider.id,
                        role=ContactRole.Type.CONTACT_POINT,
                    )
                    for project in old_projects
                    for deployment in project.deployments.all()
                    if deployment.provider is not None
                ],
            ],
            ignore_conflicts=True,
        )

    def migrate_project_contact_roles(self, old_projects):
        self.ProjectContactThrough.objects.bulk_create(
            [
                self.ProjectContactThrough(
                    id=relation.id,
                    project_id=relation.project_id,
                    contactrole_id=relation.institution_id,
                )
                for project in old_projects
                for relation in project.responsible_parties.through.objects.filter(
                    project_id=project.id
                )
            ]
        )

    def migrate_deployment_contact_roles(self, old_projects):
        self.DeploymentContactThrough.objects.bulk_create(
            [
                self.DeploymentContactThrough(
                    deployment_id=deployment.id,
                    contactrole_id=deployment.provider.id,
                )
                for project in old_projects
                for deployment in project.deployments.all()
                if deployment.provider is not None
            ]
        )

    def migrate_deployment_mobile_positions(self, old_projects):
        self.DeploymentMobilePosition.objects.bulk_create(
            [
                self.DeploymentMobilePosition(
                    id=mobile.id,
                    deployment_id=deployment.id,
                    datetime=mobile.datetime,
                    longitude=mobile.longitude,
                    latitude=mobile.latitude,
                    depth=mobile.hydrophone_depth,
                    heading=mobile.heading,
                    pitch=mobile.pitch,
                    roll=mobile.roll,
                )
                for project in old_projects
                for deployment in project.deployments.all()
                for mobile in deployment.mobileplatform_set.all()
            ]
        )

    def migrate_file_formats(self, old_projects):
        self.FileFormat.objects.bulk_create(
            [
                *[
                    self.FileFormat(
                        id=file.format.id,
                        name=file.format.name,
                    )
                    for project in old_projects
                    for deployment in project.deployments.all()
                    for channel in deployment.channelconfiguration_set.all()
                    for file in channel.file_set.all()
                ],
                *[
                    self.FileFormat(
                        id=channel.recording_format.id,
                        name=channel.recording_format.name,
                    )
                    for project in old_projects
                    for deployment in project.deployments.all()
                    for channel in deployment.channelconfiguration_set.all()
                ],
            ],
            ignore_conflicts=True,
        )
        is_unknown = (
            len(
                [
                    True
                    for project in old_projects
                    for deployment in project.deployments.all()
                    for channel in deployment.channelconfiguration_set.all()
                    for file in channel.file_set.all()
                    if file.format is None
                ]
            )
            > 0
        )
        if is_unknown:
            unknown_format, _ = self.FileFormat.objects.get_or_create(name="[Unknown]")
            self.unknown_format_id = unknown_format.id

    def migrate_files(self, old_projects):
        self.File.objects.bulk_create(
            [
                self.File(
                    id=file.id,
                    filename=file.name,
                    format_id=file.format_id
                    if file.format_id is not None
                    else self.unknown_format_id,
                    audio_properties_id=file.id,
                    storage_location=file.storage_location,
                    file_size=file.file_size,
                    accessibility=file.accessibility,
                )
                for project in old_projects
                for deployment in project.deployments.all()
                for channel in deployment.channelconfiguration_set.all()
                for file in channel.file_set.all()
            ]
        )

    def migrate_audio_properties(self, old_projects):
        self.AudioProperties.objects.bulk_create(
            [
                self.AudioProperties(
                    id=file.id,
                    sampling_frequency=file.sampling_frequency,
                    initial_timestamp=file.initial_timestamp,
                    duration=file.duration,
                    sample_depth=file.sample_depth,
                )
                for project in old_projects
                for deployment in project.deployments.all()
                for channel in deployment.channelconfiguration_set.all()
                for file in channel.file_set.all()
            ]
        )

    def migrate_channel_configuration_files(self, old_projects):
        self.ChannelConfigurationFiles.objects.bulk_create(
            [
                self.ChannelConfigurationFiles(
                    channel_configuration_id=channel.id,
                    file_id=file.id,
                )
                for project in old_projects
                for deployment in project.deployments.all()
                for channel in deployment.channelconfiguration_set.all()
                for file in channel.file_set.all()
            ]
        )

    def migrate_equipment(self, old_projects):
        all_channels = [
            channel
            for project in old_projects
            for deployment in project.deployments.all()
            for channel in deployment.channelconfiguration_set.all()
        ]
        equipments = []
        for channel in all_channels:
            provider, _ = self.Contact.objects.get_or_create(
                name=channel.recorder.model.provider.name,
                mail=channel.recorder.model.provider.contact,
                website=channel.recorder.model.provider.website,
            )
            equipments.append(
                self.Equipment(
                    id=channel.recorder.id,
                    model=channel.recorder.model.name,
                    serial_number=channel.recorder.serial_number,
                    owner=self.migration_contact,
                    provider=provider,
                    name=channel.recorder.name,
                    recorder_specification_id=channel.recorder.id,
                )
            )
            provider, _ = self.Contact.objects.get_or_create(
                name=channel.hydrophone.model.provider.name,
                mail=channel.hydrophone.model.provider.contact,
                website=channel.hydrophone.model.provider.website,
            )
            equipments.append(
                self.Equipment(
                    model=channel.hydrophone.model.name,
                    serial_number=channel.hydrophone.serial_number,
                    owner=self.migration_contact,
                    provider=provider,
                    name=channel.recorder.name,
                    hydrophone_specification_id=channel.hydrophone.id,
                )
            )
        self.Equipment.objects.bulk_create(equipments, ignore_conflicts=True)

    def migrate_recorder_specifications(self, old_projects):
        self.RecorderSpecification.objects.bulk_create(
            [
                self.RecorderSpecification(
                    id=channel.recorder.id,
                    channels_count=channel.recorder.model.number_of_channels,
                )
                for project in old_projects
                for deployment in project.deployments.all()
                for channel in deployment.channelconfiguration_set.all()
            ],
            ignore_conflicts=True,
        )

    def migrate_hydrophone_specifications(self, old_projects):
        self.HydrophoneSpecification.objects.bulk_create(
            [
                self.HydrophoneSpecification(
                    id=channel.hydrophone.id,
                    sensitivity=channel.hydrophone.sensitivity,
                    directivity=channel.hydrophone.model.directivity,
                    operating_min_temperature=channel.hydrophone.model.operating_min_temperature,
                    operating_max_temperature=channel.hydrophone.model.operating_max_temperature,
                    min_bandwidth=channel.hydrophone.model.min_bandwidth,
                    max_bandwidth=channel.hydrophone.model.max_bandwidth,
                    min_dynamic_range=channel.hydrophone.model.min_dynamic_range,
                    max_dynamic_range=channel.hydrophone.model.max_dynamic_range,
                    max_operating_depth=channel.hydrophone.model.max_operating_depth,
                    noise_floor=channel.hydrophone.model.noise_floor,
                )
                for project in old_projects
                for deployment in project.deployments.all()
                for channel in deployment.channelconfiguration_set.all()
            ],
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("metadatax", "0024_channelconfiguration_harvesttime"),
        ("metadatax_common", "0001_initial"),
        ("metadatax_acquisition", "0002_initial"),
        ("metadatax_equipment", "0001_initial"),
        ("metadatax_data", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(MigrationAction, migrations.RunPython.noop),
    ]
