# Generated by Django 3.2.25 on 2025-07-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadatax", "0026_auto_20250723_1740"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Acquisition
            SELECT setval('metadatax_acquisition_project_id_seq', (SELECT max(id) from metadatax_acquisition_project));
            SELECT setval('metadatax_acquisition_projecttype_id_seq', (SELECT max(id) from metadatax_acquisition_projecttype));
            SELECT setval('metadatax_acquisition_site_id_seq', (SELECT max(id) from metadatax_acquisition_site));
            SELECT setval('metadatax_acquisition_campaign_id_seq', (SELECT max(id) from metadatax_acquisition_campaign));
            SELECT setval('metadatax_acquisition_deployment_id_seq', (SELECT max(id) from metadatax_acquisition_deployment));
            SELECT setval('metadatax_acquisition_channelconfiguration_id_seq', (SELECT max(id) from metadatax_acquisition_channelconfiguration));
            SELECT setval('metadatax_acquisition_channelconfigurationrecorderspecif_id_seq', (SELECT max(id) from metadatax_acquisition_channelconfigurationrecorderspecification));
            SELECT setval('metadatax_acquisition_project_contacts_id_seq', (SELECT max(id) from metadatax_acquisition_project_contacts));
            SELECT setval('metadatax_acquisition_deploymentmobileposition_id_seq', (SELECT max(id) from metadatax_acquisition_deploymentmobileposition));
            
            -- Data
            SELECT setval('metadatax_data_file_id_seq', (SELECT max(id) from metadatax_data_file));
            SELECT setval('metadatax_data_audioproperties_id_seq', (SELECT max(id) from metadatax_data_audioproperties));
            SELECT setval('metadatax_acquisition_channelconfiguration_id_seq', (SELECT max(id) from metadatax_acquisition_channelconfiguration));
            """,
        ),
    ]
