name: Global check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ ready_for_review, opened, reopened, synchronize ]

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up poetry cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Check for missed migrations (don't forget to run makemigrations)
        run: |
          if [ "$(poetry run ./manage.py makemigrations --dry-run)" != "No changes detected" ]; then exit 1; fi